name: Respond on New Pick Request

on:
  issues:
    types: [labeled]

jobs:
  publish-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      - name: Publish Message
        uses: actions/github-script@v7
        if: github.event.label.name == 'Type Pick Request'
        with:
          github-token: ${{ secrets.REACT_NATIVE_BOT_REACT_WG_REACT_NATIVE_RELEASES_TOKEN }}
          script: |
            const fs = require("fs");
            const path = require("path");
            const message = fs.readFileSync(path.resolve(process.env.GITHUB_WORKSPACE, '.github/workflows/pick-request-hello-message.md'), 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
