name: Respond on New Pick Request

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  publish-message:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Message
        uses: actions/github-script@v7
        if: github.event.label.name == 'Type Pick Request'
        env:
          MESSAGE: $(cat ./pick-request-hello-message.md)
        with:
          github-token: ${{ secrets.REACT_NATIVE_BOT_REACT_WG_REACT_NATIVE_RELEASES_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: github.context.issue.number,
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              body: "${MESSAGE}"
            })
